name: sunyoubin
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.0.5


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # easy_extension:
  #   git:
  #     url: https://github.com/scadasystems/Easy-Extension.git
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

fonts:
  - family: Pretendard
    fonts:
      - assets/Pacifico-Regular.ttf

flutter:



  uses-material-design: true

